# Generated by Django 2.2.7 on 2019-11-28 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='abcd', upload_to='uploads')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
